[platformio]
src_dir = firmware/newswire

[env:esp32-s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
board_build.partitions = firmware/newswire/partitions.csv
board_build.app_partition_name = factory
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@7.4.2
    links2004/WebSockets@2.7.2
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
